import os
import glob
from PIL import Image, ImageDraw, ImageFont, ImageFilter

# Target languages
LANGUAGES = {
    'tr': {
        'name': 'Türkçe',
        'screens': [
            {
                'tag': '📍 CANLI GPS TAKİBİ',
                'title': 'Dostunuzun Konumu\nHer An Haritanızda',
                'subtitle': 'Künye okutulduğu an anlık sokak adresi ve canlı rota hazır.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ AKILLI QR KÜNYE',
                'title': 'Telefon Kamerasıyla\nTek Dokunuşta Tanıma',
                'subtitle': 'Bulan kişi uygulama indirmeden tek tıkla size ulaşır.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ANLIK BİLDİRİM',
                'title': 'Künye Okutulduğu An\nTelefonunuza Bildirim Düşer',
                'subtitle': '±3m yüksek GPS hassasiyeti ve sesli acil durum uyarısı.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ SIFIR ŞARJ DERDİ',
                'title': 'Asla Şarjı Bitmez,\nYarı Yolda Bırakmaz',
                'subtitle': '%100 pasif teknoloji. Tüy kadar hafif ve suya tam dayanıklı.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DİJİTAL SAĞLIK KARTI',
                'title': 'Alerji, Aşı ve Klinik\nBilgileri Her Zaman Yanında',
                'subtitle': 'Acil durumlarda veteriner ve sağlık notlarına anında erişim.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 KAYIP ALARM AĞI',
                'title': 'Kayıp Anında Tüm\nGüvenlik Kalkanı Devrede',
                'subtitle': 'Yüksek öncelikli acil durum alarmı ve doğrudan bulucu rotası.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 TEK TIKLA ULAŞIM',
                'title': 'WhatsApp ve Arama ile\nAnında Sahibine Ulaşın',
                'subtitle': 'Tek dokunuşla canlı konum paylaşımı ve telefon araması.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'en': {
        'name': 'English',
        'screens': [
            {
                'tag': '📍 LIVE GPS TRACKING',
                'title': 'Your Pet\'s Location\nAlways on Your Map',
                'subtitle': 'Instant street address and live GPS route when scanned.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SMART QR TAG',
                'title': 'Scannable by Any Phone\nCamera in Seconds',
                'subtitle': 'Anyone who finds your pet can reach you with one tap.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 INSTANT ALERTS',
                'title': 'Immediate Notification\nWhen Tag is Scanned',
                'subtitle': '±3m high accuracy GPS telemetry & loud acoustic alert.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ ZERO BATTERY CHARGE',
                'title': 'Never Runs Out of Battery,\nZero Maintenance',
                'subtitle': '100% passive technology. Featherlight & fully waterproof.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAL PET PROFILE',
                'title': 'Medical History, Vaccines\n& Allergies Always Handy',
                'subtitle': 'Instant emergency access to vet details and diet notes.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 LOST PET SOS SHIELD',
                'title': 'Full Emergency Shield\nActivated When Lost',
                'subtitle': 'High-priority sound alarm and direct finder navigation.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 1-TAP CONTACT',
                'title': 'Direct Call & WhatsApp\nWith the Owner',
                'subtitle': 'Instant coordinates sharing and calling with no app required.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'de': {
        'name': 'Deutsch',
        'screens': [
            {
                'tag': '📍 LIVE-GPS-TRACKING',
                'title': 'Der Standort Ihres Tieres\nJederzeit auf der Karte',
                'subtitle': 'Sofortige Straßenadresse und Live-Route beim Scannen.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SMARTE QR-MARKE',
                'title': 'Mit jeder Handykamera\nin Sekunden gescannt',
                'subtitle': 'Finder erreichen Sie mit nur einem einzigen Fingertipp.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ECHTZEIT-BENACHRICHTIGUNG',
                'title': 'Sofortiger Alarm,\nwenn die Marke gescannt wird',
                'subtitle': '±3m GPS-Genauigkeit und akustischer Notfall-Alarm.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ NIE WIEDER LADEN',
                'title': 'Kein Akku erforderlich,\n100% wartungsfrei',
                'subtitle': '100% passive Technologie. Federleicht und wasserdicht.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITALES TIERPROFIL',
                'title': 'Impfungen, Allergien\n& Tierarzt immer griffbereit',
                'subtitle': 'Schneller Zugriff auf lebenswichtige Notfall-Infos.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 NOTFALL-SOS-MODUS',
                'title': 'Maximaler Schutz\nim Ernstfall aktiviert',
                'subtitle': 'Prioritäts-Alarm und direkte Wegbeschreibung zum Tier.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 1-KLICK-KONTAKT',
                'title': 'Direktanruf & WhatsApp\nohne extra App',
                'subtitle': 'Standort teilen und Besitzer sofort anrufen.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'es': {
        'name': 'Español',
        'screens': [
            {
                'tag': '📍 RASTREO GPS EN VIVO',
                'title': 'La Ubicación de tu Mascota\nSiempre en tu Mapa',
                'subtitle': 'Dirección exacta y ruta en tiempo real al escanear la placa.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ PLACA QR INTELIGENTE',
                'title': 'Escaneable con Cualquier\nCámara en Segundos',
                'subtitle': 'Quien la encuentre te contactará con un solo toque.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ALERTA INSTANTÁNEA',
                'title': 'Notificación Inmediata\nal Escanear la Placa',
                'subtitle': 'GPS de alta precisión (±3m) y alarma sonora de emergencia.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ CERO BATERÍA',
                'title': 'Sin Cargar Baterías,\nProtección Permanente',
                'subtitle': 'Tecnología 100% pasiva. Ultraligera y resistente al agua.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 PERFIL DIGITAL COMPLETO',
                'title': 'Vacunas, Alergias y Datos\nde Salud Siempre a Mano',
                'subtitle': 'Acceso directo a datos del veterinario y cuidados especiales.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 MODO SOS EXTRAVÍO',
                'title': 'Escudo de Seguridad\nTotal en Emergencias',
                'subtitle': 'Alarma prioritaria y guía de rescate para quien lo encuentre.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 CONTACTO EN 1 TOQUE',
                'title': 'Llamada y WhatsApp Directo\nSin Descargar Apps',
                'subtitle': 'Envío instantáneo de coordenadas y comunicación directa.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'fr': {
        'name': 'Français',
        'screens': [
            {
                'tag': '📍 SUIVI GPS EN DIRECT',
                'title': 'La Position de Votre Animal\nToujours sur Votre Carte',
                'subtitle': 'Adresse exacte et itinéraire GPS en direct dès le scan.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ MÉDAILLE QR INTELLIGENTE',
                'title': 'Scannable avec Tout\nSmartphone en 1 Seconde',
                'subtitle': 'La personne qui le trouve vous contacte en un seul geste.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ALERTE INSTANTANÉE',
                'title': 'Notification Immédiate\nDès que la Médaille est Scannée',
                'subtitle': 'GPS haute précision (±3m) et alarme sonore prioritaire.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ ZÉRO RECHARGE',
                'title': 'Aucune Batterie Requise,\nProtection Illimitée',
                'subtitle': 'Technologie 100% passive. Ultra-légère et étanche à l\'eau.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 CARNET DE SANTÉ NUMÉRIQUE',
                'title': 'Vaccins, Allergies et Soins\nToujours à Portée de Main',
                'subtitle': 'Accès d\'urgence aux coordonnées du vétérinaire et du maître.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 BOUCLIER SOS PERDU',
                'title': 'Protection Maximale\nActivée en Cas de Perte',
                'subtitle': 'Alerte sonore urgente et navigation guidée vers l\'animal.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 CONTACT EN 1 CLIC',
                'title': 'Appel & WhatsApp Direct\nSans Télécharger d\'Appli',
                'subtitle': 'Partage de coordonnées GPS et appel direct avec le propriétaire.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'it': {
        'name': 'Italiano',
        'screens': [
            {
                'tag': '📍 TRACCIAMENTO GPS LIVE',
                'title': 'La Posizione del Tuo Animale\nSempre sulla Mappa',
                'subtitle': 'Indirizzo civico e percorso live non appena la medaglietta viene scansionata.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ MEDAGLIETTA QR SMART',
                'title': 'Scansionabile con Qualsiasi\nFotocamera in 1 Secondo',
                'subtitle': 'Chi lo trova può contattarti con un solo semplice tocco.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 NOTIFICA IMMEDIATA',
                'title': 'Avviso Istantaneo\nQuando Viene Scansionato',
                'subtitle': 'GPS ad altissima precisione (±3m) e allarme sonoro d\'urgenza.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ ZERO BATTERIA',
                'title': 'Nessuna Ricarica Necessaria,\nSempre Attivo',
                'subtitle': 'Tecnologia 100% passiva. Leggerissima e impermeabile.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 PROFILO DIGITALE PET',
                'title': 'Vaccini, Allergie e Clinica\nSempre con Te',
                'subtitle': 'Accesso istantaneo ai contatti del veterinario e note mediche.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 SCUDO SOS SMARRIMENTO',
                'title': 'Massima Sicurezza\nin Caso di Emergenza',
                'subtitle': 'Allarme prioritario e indicazioni stradali per il ritrovatore.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 CONTATTO IN 1 TOCCO',
                'title': 'Chiamata & WhatsApp Diretto\nSenza Scaricare App',
                'subtitle': 'Condivisione coordinate e contatto rapido con il proprietario.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'pt': {
        'name': 'Português',
        'screens': [
            {
                'tag': '📍 RASTREAMENTO GPS EM TEMPO REAL',
                'title': 'A Localização do seu Pet\nSempre no seu Mapa',
                'subtitle': 'Endereço exato e rota em tempo real assim que a tag é escaneada.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ TAG QR INTELIGENTE',
                'title': 'Escaneável com Qualquer\nCâmera em Segundos',
                'subtitle': 'Quem encontrar seu amigo pode falar com você em 1 toque.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ALERTA INSTANTÂNEO',
                'title': 'Notificação Imediata\nno Momento do Escaneamento',
                'subtitle': 'GPS de alta precisão (±3m) e alarme sonoro de emergência.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ ZERO BATERIA',
                'title': 'Nunca Acaba a Bateria,\nProteção Vitalícia',
                'subtitle': 'Tecnologia 100% passiva. Super leve e à prova d\'água.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 PERFIL DIGITAL DO PET',
                'title': 'Vacinas, Alergias e Veterinário\nSempre à Mão',
                'subtitle': 'Acesso rápido para dados médicos e cuidados especiais.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 ESCUDO SOS PERDIDO',
                'title': 'Modo de Emergência\nTotalmente Ativado',
                'subtitle': 'Alarme de alta prioridade e navegação direta para o resgate.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 CONTATO EM 1 TOQUE',
                'title': 'Ligação e WhatsApp Direto\nSem Instalar Aplicativos',
                'subtitle': 'Envio de coordenadas GPS e contato direto com o tutor.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'nl': {
        'name': 'Nederlands',
        'screens': [
            {
                'tag': '📍 LIVE GPS-LOCATIE',
                'title': 'De Locatie van je Huisdier\nAltijd op je Kaart',
                'subtitle': 'Direct adres en live route zodra de penning wordt gescand.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SLIMME QR-PENNING',
                'title': 'Met elke Smartphonecamera\nDirect te Scannen',
                'subtitle': 'De vinder kan met één simpele tik contact met je opnemen.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 DIRECTE MELDING',
                'title': 'Meteen een Melding\nbij het Scannen van de Penning',
                'subtitle': '±3m nauwkeurige GPS en akoestisch noodalarm.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ NOOIT OPLADEN',
                'title': 'Geen Batterij Nodig,\nAltijd Beschermd',
                'subtitle': '100% passieve technologie. Vederlicht en waterdicht.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAAL DIERENPASPOORT',
                'title': 'Vaccinaties, Allergieën &\nDierenarts Altijd Paraat',
                'subtitle': 'Directe toegang tot medische notities in noodgevallen.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 VERMIST SOS-SCHILD',
                'title': 'Volledige Noodbescherming\nGeactiveerd bij Vermissing',
                'subtitle': 'Prioriteitsalarm en directe route voor de vinder.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 1-KLIK CONTACT',
                'title': 'Direct Bellen & WhatsApp\nZonder Extra App',
                'subtitle': 'Deel direct GPS-coördinaten en bel de eigenaar.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'ru': {
        'name': 'Русский',
        'screens': [
            {
                'tag': '📍 ОНЛАЙН GPS-ТРЕКИНГ',
                'title': 'Местоположение Питомца\nВсегда на Вашей Карте',
                'subtitle': 'Точный адрес и маршрут сразу при сканировании адресника.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ УМНЫЙ QR-АДРЕСНИК',
                'title': 'Сканируется Камерой\nЛюбого Смартфона за 1 Секунду',
                'subtitle': 'Нашедший сможет связаться с вами в одно касание.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 МГНОВЕННЫЙ СИГНАЛ',
                'title': 'Уведомление на Телефон\nПри Сканировании Адресника',
                'subtitle': 'GPS с точностью до ±3м и громкий звуковой сигнал тревоги.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ БЕЗ БАТАРЕЕК И ЗАРЯДКИ',
                'title': 'Никогда Не Разрядится,\nНе Требует Обслуживания',
                'subtitle': '100% пассивная технология. Невероятно легкий и водонепроницаемый.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 ЦИФРОВОЙ ПРОФИЛЬ ПИТОМЦА',
                'title': 'Прививки, Аллергии и\nКонтакты Ветклиники Под Рукой',
                'subtitle': 'Мгновенный доступ к медицинской информации в экстренной ситуации.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 РЕЖИМ SOS ПРИ ПОТЕРЕ',
                'title': 'Экстренный Щит Защиты\nВключается Мгновенно',
                'subtitle': 'Приоритетная тревога и навигация прямо к питомцу.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 СВЯЗЬ В 1 КЛИК',
                'title': 'Звонок и WhatsApp\nБез Установки Приложений',
                'subtitle': 'Отправка GPS-координат и прямой звонок владельцу.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'ar': {
        'name': 'العربية',
        'screens': [
            {
                'tag': '📍 تتبع GPS المباشر',
                'title': 'موقع أليفك الدقيق\nدائماً على خريطتك',
                'subtitle': 'عنوان الشارع ومسار مباشر بمجرد مسح القلادة الذكية.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ قلادة QR الذكية',
                'title': 'مسح فوري بكاميرا\nأي هاتف في ثانية واحدة',
                'subtitle': 'يمكن لمن يجد أليفك التواصل معك بلمسة زر واحدة.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 تنبيهات فورية',
                'title': 'إشعار فوري على هاتفك\nعند مسح القلادة',
                'subtitle': 'دقة GPS عالية (±3م) وتنبيه صوتي عالي للطوارئ.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ بدون بطاريات أو شحن',
                'title': 'لا تنفد بطاريتها أبداً\nحماية مستمرة مدى الحياة',
                'subtitle': 'تقنية سلبية 100%. خفيفة الوزن ومقاومة للماء تماماً.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 الملف الرقمي الشامل',
                'title': 'اللقاحات، الحساسية والعيادة\nدائماً معك في كل مكان',
                'subtitle': 'وصول سريع للمعلومات الطبية وتعليمات العناية في الطوارئ.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 درع الطوارئ SOS',
                'title': 'حماية قصوى مفعلة\nفور فقدان الأليف',
                'subtitle': 'إنذار ذو أولوية قصوى وتوجيه مباشر للوصول للأليف.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 اتصال بلمسة واحدة',
                'title': 'اتصال وواتساب مباشر\nبدون تنزيل أي تطبيقات',
                'subtitle': 'مشاركة إحداثيات الموقع والاتصال بالمالك فوراً.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'ja': {
        'name': '日本語',
        'screens': [
            {
                'tag': '📍 リアルタイムGPS追跡',
                'title': '大切なペットの居場所を\nいつでもマップで確認',
                'subtitle': 'タグが読み取られると正確な住所とルートを即座に表示。',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ スマートQRタグ',
                'title': 'スマホのカメラで\nわずか1秒で認識',
                'subtitle': '見つけてくれた人がワンタップで飼い主に直接連絡できます。',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 リアルタイム通知',
                'title': 'タグが読み取られた瞬間に\nスマホへ通知',
                'subtitle': '±3mの高精度GPS測位と緊急アラーム音でお知らせ。',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ 充電不要・電池不要',
                'title': 'バッテリー切れの心配なし\nずっと安心が続く',
                'subtitle': '100%パッシブ技術。羽のように軽く、完全防水仕様。',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 デジタル健康カルテ',
                'title': 'ワクチン・アレルギー・病院情報\nすべて手元で管理',
                'subtitle': '緊急時にも獣医師や健康メモをすぐに確認できます。',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 迷子緊急SOSモード',
                'title': '迷子時にも万全の\nセキュリティシールド',
                'subtitle': '最優先アラームと発見者用ナビゲーションが即時起動。',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 ワンタップ連絡',
                'title': 'アプリ不要で電話＆\nメッセージ即時連絡',
                'subtitle': 'GPS位置情報共有と飼い主への直接通話が可能。',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'ko': {
        'name': '한국어',
        'screens': [
            {
                'tag': '📍 실시간 GPS 위치 추적',
                'title': '소중한 반려동물의 위치\n언제나 지도에서 확인',
                'subtitle': '인식표 스캔 즉시 상세 주소와 실시간 경로를 전송합니다.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ 스마트 QR 인식표',
                'title': '스마트폰 카메라로\n1초 만에 바로 스캔',
                'subtitle': '발견자가 앱 설치 없이 터치 한 번으로 보호자에게 연락합니다.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 즉각적인 알림',
                'title': '인식표 스캔 즉시\n스마트폰으로 알림 전송',
                'subtitle': '±3m 초정밀 GPS 및 긴급 비상 알림음 지원.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ 충전 걱정 제로',
                'title': '배터리 충전 필요 없이\n평생 안전하게 보호',
                'subtitle': '100% 무전원 패시브 기술. 깃털처럼 가볍고 완전 방수 지원.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 디지털 반려동물 프로필',
                'title': '예방접종, 알레르기 및\n병원 정보를 한눈에',
                'subtitle': '응급 상황 시 수의사 정보와 주의사항 즉시 확인 가능.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 실종 방지 SOS 모드',
                'title': '실종 시 즉각 가동되는\n강력한 비상 보안 쉴드',
                'subtitle': '최고 우선순위 경보음 및 발견자 전용 안내 화면 제공.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 원터치 직통 연락',
                'title': '앱 설치 없이 전화 및\n메시지로 즉시 연결',
                'subtitle': 'GPS 실시간 좌표 공유 및 보호자 즉시 통화 지원.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'zh': {
        'name': '简体中文',
        'screens': [
            {
                'tag': '📍 实时 GPS 定位',
                'title': '爱宠的精准位置\n时刻显示在地图上',
                'subtitle': '扫码瞬间获取详细街道地址与实时导航路线。',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ 智能 QR 吊牌',
                'title': '手机相机一扫即识\n无需额外下载应用',
                'subtitle': '任何拾到爱宠的人均可一键直接联系主人。',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 实时警报通知',
                'title': '吊牌被扫描瞬间\n手机即刻收到通知',
                'subtitle': '±3米高精度 GPS 定位与紧急响铃警报。',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ 零电量负担',
                'title': '永久无需充电\n终身守护不掉线',
                'subtitle': '100% 无源被动技术，轻盈如羽且全面防水。',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 电子健康档案',
                'title': '疫苗、过敏史与诊所信息\n随时一手掌握',
                'subtitle': '紧急时刻即刻查阅兽医电话与健康备注。',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 走失 SOS 护盾',
                'title': '爱宠走失紧急状态\n全面启动安全护盾',
                'subtitle': '最高级别声光报警与拾到者指引路线。',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 一键直连沟通',
                'title': '直接电话与信息直达\n省时高效寻宠',
                'subtitle': '即时发送经纬度坐标并与主人直接通话。',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'pl': {
        'name': 'Polski',
        'screens': [
            {
                'tag': '📍 LOKALIZACJA GPS NA ŻYWO',
                'title': 'Położenie Twojego Pupila\nZawsze na Twojej Mapie',
                'subtitle': 'Dokładny adres i trasa na żywo natychmiast po zeskanowaniu.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ INTELIGENTNA ZAWIESZKA QR',
                'title': 'Skanowanie Dowolnym\nSmartfonem w 1 Sekundę',
                'subtitle': 'Znalazca może skontaktować się z Tobą jednym kliknięciem.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 NATYCHMIASTOWY ALERT',
                'title': 'Powiadomienie na Telefon\npo Zeskanowaniu Adresówki',
                'subtitle': 'Precyzyjny GPS (±3m) i głośny alarm ratunkowy.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ ZERO ŁADOWANIA',
                'title': 'Nigdy Się Nie Rozładuje,\nZawsze Gotowa do Pomocy',
                'subtitle': 'Technologia 100% pasywna. Ultralekka i w pełni wodoodporna.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 CYFROWY PROFIL ZWIERZAKA',
                'title': 'Szczepienia, Alergie i\nWeterynarz Zawsze pod Ręką',
                'subtitle': 'Błyskawiczny dostęp do ważnych danych medycznych.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 TARCZA SOS ZAGINIĘCIA',
                'title': 'Maksymalne Bezpieczeństwo\nw Nagłych Wypadkach',
                'subtitle': 'Priorytetowy alarm i wskazówki nawigacyjne dla znalazcy.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 KONTAKT W 1 KLIK',
                'title': 'Połączenie & WhatsApp\nBez Pobierania Aplikacji',
                'subtitle': 'Udostępnianie współrzędnych i bezpośredni kontakt z właścicielem.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'sv': {
        'name': 'Svenska',
        'screens': [
            {
                'tag': '📍 LIVE GPS-SPÅRNING',
                'title': 'Ditt Husdjurs Plats\nAlltid på Din Karta',
                'subtitle': 'Exakt adress och live-rutt så fort brickan skannas.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SMART QR-BRICKA',
                'title': 'Skannas med Vilken\nMobilkamera som Helst',
                'subtitle': 'Upphittaren kan nå dig med ett enkelt knapptryck.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 OMEDELBAR NOTIS',
                'title': 'Notis till Mobilen\nså Fort Brickan Skannas',
                'subtitle': 'Hög GPS-precision (±3m) och högljutt nödlarm.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ INGEN LADDNING KRÄVS',
                'title': 'Batteriet Tar Aldrig Slut,\nAlltid Tryggt',
                'subtitle': '100% passiv teknologi. Fjäderlätt och helt vattentät.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAL HUSDJURSPROFIL',
                'title': 'Vaccin, Allergier &\nVeterinär Alltid Till Hands',
                'subtitle': 'Snabb tillgång till medicinsk information i nödsituationer.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 BORTTAPPAD SOS-SKÖLD',
                'title': 'Full Säkerhetssköld\nAktiverad vid Förlust',
                'subtitle': 'Prioriterat larm och vägbeskrivning för upphittaren.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 KONTAKT MED 1 KLICK',
                'title': 'Direktsamtal & WhatsApp\nUtan Extra Appar',
                'subtitle': 'Dela GPS-koordinater och ring ägaren direkt.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'no': {
        'name': 'Norsk',
        'screens': [
            {
                'tag': '📍 LIVE GPS-SPORING',
                'title': 'Kjæledyrets Posisjon\nAlltid på Kartet Ditt',
                'subtitle': 'Nøyaktig adresse og rute i sanntid når brikken skannes.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SMART QR-BRIKKE',
                'title': 'Skannes med Hvilket som\nHelst Mobilkamera',
                'subtitle': 'Finneren kan kontakte deg med ett enkelt trykk.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ØYEBLIKKELIG VARSEL',
                'title': 'Varsel på Telefonen\nnår Brikken Skannes',
                'subtitle': 'Høy GPS-nøyaktighet (±3m) og høyt nødsignal.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ TRENGER ALDRI LADING',
                'title': 'Går Aldri Tom for Strøm,\nAlltid Trygg',
                'subtitle': '100% passiv teknologi. Fjærlett og vanntett.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAL KJÆLEDYRPROFIL',
                'title': 'Vaksiner, Allergier og\nVeterinær Alltid Tilgjengelig',
                'subtitle': 'Rask tilgang til helseopplysninger i nødsituasjoner.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 MISTET SOS-SKJOLD',
                'title': 'Full Sikkerhetsbeskyttelse\nAktivert ved Tap',
                'subtitle': 'Prioritert alarm og navigasjon for finneren.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 1-TRYKKS KONTAKT',
                'title': 'Direkte Anrop & WhatsApp\nUten å Laste Ned App',
                'subtitle': 'Del GPS-posisjon og ring eieren umiddelbart.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'da': {
        'name': 'Dansk',
        'screens': [
            {
                'tag': '📍 LIVE GPS-SPORING',
                'title': 'Dit Kæledyrs Placering\nAltid på Dit Kort',
                'subtitle': 'Nøjagtig adresse og live-rute, så snart tegnet scannes.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ SMART QR-TEGN',
                'title': 'Scannes med Enhver\nSmartphone på 1 Sekund',
                'subtitle': 'Finderen kan kontakte dig med et enkelt tryk.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 ØJEBLIKKELIG BESKED',
                'title': 'Besked på Telefonen\nnår Tegnet Bliver Scannet',
                'subtitle': 'Høj GPS-præcision (±3m) og høj nødalarm.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ SKAL ALDRIG OPLADES',
                'title': 'Løber Aldrig Tør for Strøm,\nAltid Sikker',
                'subtitle': '100% passiv teknologi. Fjerlet og helt vandtæt.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAL KÆLEDYRSPROFIL',
                'title': 'Vacciner, Allergier og\nDyrlæge Altid ved Hånden',
                'subtitle': 'Hurtig adgang til helbredsoplysninger i nødsituationer.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 FORSVUNDET SOS-SKJOLD',
                'title': 'Fuld Sikkerhedsbeskyttelse\nAktiveret ved Bortkomst',
                'subtitle': 'Prioriteret alarm og vejvisning for finderen.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 KONTAKT MED 1 KLIK',
                'title': 'Direkte Opkald & WhatsApp\nUden App-Download',
                'subtitle': 'Del GPS-koordinater og ring til ejeren med det samme.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'fi': {
        'name': 'Suomi',
        'screens': [
            {
                'tag': '📍 LIVE GPS-PAIKANNUS',
                'title': 'Lemmikkisi Sijainti\nAina Kartallasi',
                'subtitle': 'Tarkka katuosoite ja reitti heti laatan skannauksen jälkeen.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ ÄLYKÄS QR-LAATTA',
                'title': 'Skannattavissa Millä\nTahansa Älypuhelimella',
                'subtitle': 'Löytäjä saa sinuun yhteyden yhdellä napautuksella.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 VÄLITÖN ILMOITUS',
                'title': 'Ilmoitus Puhelimeesi\nheti kun Laatta Luetaan',
                'subtitle': 'Tarkka GPS (±3m) ja kuuluva hätähälytysääni.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ EI LATAUSTARVETTA',
                'title': 'Akku Ei Lopu Koskaan,\nJatkuva Turva',
                'subtitle': '100% passiivinen teknologia. Höyhenenkevyt ja vedenpitävä.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 DIGITAALINEN LEMMIKKIPROFIILI',
                'title': 'Rokotukset, Allergiat ja\nEläinlääkäritiedot Aina Mukana',
                'subtitle': 'Nopea pääsy terveystietoihin hätätilanteissa.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 KADONNUT SOS-KILPI',
                'title': 'Täysi Turvasuoja\nPäällä Katoamistilanteessa',
                'subtitle': 'Ensisijainen hälytys ja opastus löytäjälle.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 YHTEYS YHDELLÄ KOSKETUKSELLA',
                'title': 'Suora Puhelu & WhatsApp\nIlman Erillistä Sovellusta',
                'subtitle': 'GPS-koordinaattien jako ja suora puhelu omistajalle.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'id': {
        'name': 'Bahasa Indonesia',
        'screens': [
            {
                'tag': '📍 PELACAKAN GPS LANGSUNG',
                'title': 'Lokasi Hewan Peliharaan\nSelalu Ada di Peta Anda',
                'subtitle': 'Alamat jalan instan dan rute langsung saat tag dipindai.',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ TAG QR PINTAR',
                'title': 'Dapat Dipindai Kamera HP\nDalam Hitungan Detik',
                'subtitle': 'Penemu hewan Anda dapat menghubungi Anda dengan satu ketukan.',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 NOTIFIKASI INSTAN',
                'title': 'Pemberitahuan Langsung\nSaat Tag Dipindai',
                'subtitle': 'Akurasi GPS tinggi (±3m) dan alarm suara darurat.',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ TANPA BATERAI',
                'title': 'Tidak Perlu Dicas,\nPerlindungan Seumur Hidup',
                'subtitle': 'Teknologi 100% pasif. Sangat ringan dan tahan air.',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 PROFIL DIGITAL LENGKAP',
                'title': 'Vaksin, Alergi & Klinik\nSelalu Dalam Genggaman',
                'subtitle': 'Akses cepat ke catatan medis hewan dalam kondisi darurat.',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 PERISAI SOS HILANG',
                'title': 'Perlindungan Darurat Penuh\nAktif Saat Hewan Hilang',
                'subtitle': 'Alarm prioritas tinggi dan panduan arah bagi penemu.',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 KONTAK 1 KETUKAN',
                'title': 'Telepon & WhatsApp Langsung\nTanpa Unduh Aplikasi',
                'subtitle': 'Berbagi koordinat GPS dan telepon langsung dengan pemilik.',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    },
    'hi': {
        'name': 'हिन्दी',
        'screens': [
            {
                'tag': '📍 लाइव GPS ट्रैकिंग',
                'title': 'आपके पालतू का स्थान\nहमेशा आपके मैप पर',
                'subtitle': 'टैग स्कैन होते ही तुरंत पता और लाइव रूट तैयार।',
                'color_top': '#E0F2FE',
                'color_bot': '#FAF7F2',
                'pill_bg': '#BAE6FD',
                'pill_txt': '#0369A1',
            },
            {
                'tag': '🏷️ स्मार्ट QR टैग',
                'title': 'किसी भी फोन कैमरे से\nसेकंडों में स्कैन करें',
                'subtitle': 'पाने वाला व्यक्ति सिर्फ एक टैप में आपसे संपर्क कर सकता है।',
                'color_top': '#DCFCE7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#86EFAC',
                'pill_txt': '#047857',
            },
            {
                'tag': '🔔 तत्काल सूचना',
                'title': 'टैग स्कैन होते ही\nफोन पर नोटिफिकेशन अलर्ट',
                'subtitle': '±3m उच्च GPS सटीकता और तेज़ आपातकालीन अलार्म।',
                'color_top': '#E0E7FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#C7D2FE',
                'pill_txt': '#3730A3',
            },
            {
                'tag': '⚡ बिना बैटरी चार्जिंग',
                'title': 'कभी बैटरी खत्म नहीं होती,\nआजीवन सुरक्षा',
                'subtitle': '100% पैसिव तकनीक। बहुत हल्का और पूरी तरह से वाटरप्रूफ।',
                'color_top': '#FEF3C7',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FDE68A',
                'pill_txt': '#B45309',
            },
            {
                'tag': '🐾 डिजिटल पेट प्रोफाइल',
                'title': 'वैक्सीन, एलर्जी व क्लिनिक\nकी जानकारी हमेशा साथ',
                'subtitle': 'आपात स्थिति में डॉक्टर और स्वास्थ्य नोट तुरंत देखें।',
                'color_top': '#F3E8FF',
                'color_bot': '#FAF7F2',
                'pill_bg': '#DDD6FE',
                'pill_txt': '#6D28D9',
            },
            {
                'tag': '🚨 लॉस्ट SOS शील्ड',
                'title': 'खो जाने पर आपातकालीन\nसुरक्षा शील्ड सक्रिय',
                'subtitle': 'उच्च प्राथमिकता वाला अलार्म और खोजने वाले के लिए सीधा मार्ग।',
                'color_top': '#FFE4E6',
                'color_bot': '#FAF7F2',
                'pill_bg': '#FECDD3',
                'pill_txt': '#BE123C',
            },
            {
                'tag': '💬 1-टैप डायरेक्ट संपर्क',
                'title': 'बिना ऐप डाउनलोड किए\nकॉल और व्हाट्सएप करें',
                'subtitle': 'लाइव GPS लोकेशन साझा करें और मालिक से सीधे बात करें।',
                'color_top': '#D1FAE5',
                'color_bot': '#FAF7F2',
                'pill_bg': '#A7F3D0',
                'pill_txt': '#047857',
            }
        ]
    }
}
